device: 'cpu'

data_path: '/content/drive/MyDrive/bible.txt'
batch_sz: 64
window_sz: 256
train_val_percentage: 0.8


dim: 256
n_layers: 12
head_dim: 128
n_heads: 32
context_len: 0
dropout: 0.2


max_length: 50